: Scan with Detekt

on:
  push:
    branches: [ next, main ]
  pull_request:
    branches: [ next, main ]

env:
  DETEKT_RELEASE_TAG: v1.15.0

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "detekt"
      uses: natiginfo/action-detekt-all@1.20.0
