name: Scan with Detekt

on:
  push:
    branches: [ main, release, next ]
  pull_request:
    branches: [ main, release, next ]

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.20.0
        with:
          args: --build-upon-default-config --config detekt.yml
